# Instructor Do: Decision Trees

In [2]:
# Initial imports
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

## Loading and Preprocessing Loans Encoded Data

In [3]:
# Loading data
file_path = Path("../Resources/loans_data_encoded.csv")
df_loans = pd.read_csv(file_path)
df_loans.head()

amount  term  age  bad  month_num  education_Bachelor  \
0    1000    30   45    0          6                   0   
1    1000    30   50    0          7                   1   
2    1000    30   33    0          8                   1   
3    1000    15   27    0          9                   0   
4    1000    30   28    0         10                   0   

   education_High School or Below  education_Master or Above  \
0                               1                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   

   education_college  gender_female  gender_male  
0                  0              0            1  
1                  0              1            0  
2                  0              1            0  
3                  1              0            1  
4                  1              1            0

In [4]:
# Define features set
X = df_loans.copy()
X = X.drop("bad", axis=1)
X.head()

amount  term  age  month_num  education_Bachelor  \
0    1000    30   45          6                   0   
1    1000    30   50          7                   1   
2    1000    30   33          8                   1   
3    1000    15   27          9                   0   
4    1000    30   28         10                   0   

   education_High School or Below  education_Master or Above  \
0                               1                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   

   education_college  gender_female  gender_male  
0                  0              0            1  
1                  0              1            0  
2                  0              1            0  
3                  1              0            1  
4                  1              1            0

In [5]:
# Define target vector
y = df_loans["bad"].values.reshape(-1, 1)
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [7]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [8]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(375, 10)
(125, 10)
(375, 1)
(125, 1)


In [9]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [10]:
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)

(400, 10)
(100, 10)
(400, 1)
(100, 1)


In [11]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [12]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [15]:
X_scaler

StandardScaler()

In [14]:
X_train

amount  term  age  month_num  education_Bachelor  \
249    1000    15   35         11                   1   
477    1000    30   27         12                   0   
442    1000    30   24         10                   0   
443    1000    30   26          7                   0   
50      800    15   27         12                   0   
..      ...   ...  ...        ...                 ...   
105    1000    30   30          6                   0   
40     1000    15   32          9                   0   
407    1000    30   26          9                   0   
470    1000    15   32          9                   0   
197    1000    15   40          8                   0   

     education_High School or Below  education_Master or Above  \
249                               0                          0   
477                               0                          0   
442                               1                          0   
443                               0                          0   
50                                0                          0   
..                              ...                        ...   
105                               0                          0   
40                                0                          0   
407                               1                          0   
470                               1                          0   
197                               0                          0   

     education_college  gender_female  gender_male  
249                  0              1            0  
477                  1              0            1  
442                  0              0            1  
443                  1              1            0  
50                   1              1            0  
..                 ...            ...          ...  
105                  1              0            1  
40                   1              1            0  
407                  0              0            1  
470                  0              0            1  
197                  1              0            1  

[375 rows x 10 columns]

In [16]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [17]:
X_train_scaled

array([[ 0.49582979, -0.93913666,  0.62959256, ..., -0.93541435,
         2.38671921, -2.38671921],
       [ 0.49582979,  0.92029442, -0.69123099, ...,  1.06904497,
        -0.41898519,  0.41898519],
       [ 0.49582979,  0.92029442, -1.18653982, ..., -0.93541435,
        -0.41898519,  0.41898519],
       ...,
       [ 0.49582979,  0.92029442, -0.85633394, ..., -0.93541435,
        -0.41898519,  0.41898519],
       [ 0.49582979, -0.93913666,  0.13428373, ..., -0.93541435,
        -0.41898519,  0.41898519],
       [ 0.49582979, -0.93913666,  1.45510728, ...,  1.06904497,
        -0.41898519,  0.41898519]])

## Fitting the Decision Tree Model

In [18]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [19]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)

## Making Predictions Using the Tree Model

In [20]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)

In [21]:
predictions

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0], dtype=int64)

## Model Evaluation

In [15]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [16]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))


Confusion Matrix


Predicted 0  Predicted 1
Actual 0           54           30
Actual 1           23           18

Accuracy Score : 0.576
Classification Report
              precision    recall  f1-score   support

           0       0.70      0.64      0.67        84
           1       0.38      0.44      0.40        41

    accuracy                           0.58       125
   macro avg       0.54      0.54      0.54       125
weighted avg       0.59      0.58      0.58       125

